services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reporter_db
      POSTGRES_USER: reporter_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings

volumes:
  postgres_data: